-- Demo catalogue for local development and the PoC environment (profile: demo).
insert into product (id, name, description, category, brand, price, currency, stock_quantity, version, created_at, updated_at) values
    (gen_random_uuid(), 'Sony WH-1000XM5 Wireless Headphones', 'Industry-leading noise cancelling over-ear wireless headphones with 30-hour battery life.', 'audio', 'Sony', 349.00, 'EUR', 25, 0, now(), now()),
    (gen_random_uuid(), 'Sony WH-CH520 Wireless Headphones', 'Lightweight on-ear wireless headphones with 50-hour battery and quick charge.', 'audio', 'Sony', 49.99, 'EUR', 120, 0, now(), now()),
    (gen_random_uuid(), 'JBL Tune 520BT Wireless Headphones', 'On-ear Bluetooth headphones with JBL Pure Bass sound and multipoint connection.', 'audio', 'JBL', 44.90, 'EUR', 80, 0, now(), now()),
    (gen_random_uuid(), 'Anker Soundcore Life Q30 Wireless Headphones', 'Hybrid active noise cancelling headphones with 40-hour playtime.', 'audio', 'Anker', 79.99, 'EUR', 0, 0, now(), now()),
    (gen_random_uuid(), 'Bose QuietComfort Ultra Headphones', 'Premium wireless noise cancelling headphones with spatial audio.', 'audio', 'Bose', 449.95, 'EUR', 12, 0, now(), now()),
    (gen_random_uuid(), 'Sennheiser HD 450BT', 'Wireless over-ear headphones with active noise cancellation and deep bass.', 'audio', 'Sennheiser', 99.00, 'EUR', 34, 0, now(), now()),
    (gen_random_uuid(), 'Apple AirPods Pro (2nd generation)', 'In-ear wireless earbuds with active noise cancellation and USB-C case.', 'audio', 'Apple', 279.00, 'EUR', 60, 0, now(), now()),
    (gen_random_uuid(), 'Samsung Galaxy Buds FE', 'Wireless earbuds with active noise cancelling and comfortable wingtip fit.', 'audio', 'Samsung', 69.00, 'EUR', 45, 0, now(), now()),
    (gen_random_uuid(), 'Sony WF-C700N Earbuds', 'Compact wireless noise cancelling earbuds with IPX4 water resistance.', 'audio', 'Sony', 89.00, 'EUR', 0, 0, now(), now()),
    (gen_random_uuid(), 'JBL Flip 6 Portable Speaker', 'Waterproof portable Bluetooth speaker with powerful sound and 12-hour battery.', 'audio', 'JBL', 119.00, 'EUR', 50, 0, now(), now()),
    (gen_random_uuid(), 'Anker Soundcore 2 Bluetooth Speaker', 'Portable wireless speaker with 24-hour playtime and IPX7 waterproofing.', 'audio', 'Anker', 39.99, 'EUR', 200, 0, now(), now()),
    (gen_random_uuid(), 'Bose SoundLink Flex', 'Rugged portable Bluetooth speaker that floats in water.', 'audio', 'Bose', 149.95, 'EUR', 18, 0, now(), now()),
    (gen_random_uuid(), 'Sonos Era 100', 'Smart wireless speaker with stereo sound and voice control.', 'audio', 'Sonos', 279.00, 'EUR', 9, 0, now(), now()),
    (gen_random_uuid(), 'Logitech MX Keys S Wireless Keyboard', 'Advanced illuminated wireless keyboard for Mac and Windows.', 'computing', 'Logitech', 119.99, 'EUR', 40, 0, now(), now()),
    (gen_random_uuid(), 'Logitech K380 Multi-Device Keyboard', 'Compact Bluetooth keyboard that switches between three devices.', 'computing', 'Logitech', 39.99, 'EUR', 150, 0, now(), now()),
    (gen_random_uuid(), 'Keychron K2 Mechanical Keyboard', 'Wireless mechanical keyboard with hot-swappable switches and RGB backlight.', 'computing', 'Keychron', 89.00, 'EUR', 22, 0, now(), now()),
    (gen_random_uuid(), 'Logitech MX Master 3S Mouse', 'Wireless performance mouse with quiet clicks and 8K DPI sensor.', 'computing', 'Logitech', 99.99, 'EUR', 70, 0, now(), now()),
    (gen_random_uuid(), 'Razer DeathAdder V3 Gaming Mouse', 'Ultra-lightweight wired ergonomic esports mouse.', 'computing', 'Razer', 69.99, 'EUR', 0, 0, now(), now()),
    (gen_random_uuid(), 'Apple Magic Mouse', 'Wireless rechargeable mouse with multi-touch surface.', 'computing', 'Apple', 85.00, 'EUR', 30, 0, now(), now()),
    (gen_random_uuid(), 'Dell UltraSharp 27 4K Monitor', '27-inch 4K USB-C hub monitor with IPS Black technology.', 'computing', 'Dell', 629.00, 'EUR', 8, 0, now(), now()),
    (gen_random_uuid(), 'LG 27GP850 Gaming Monitor', '27-inch QHD Nano IPS gaming monitor with 180Hz refresh rate.', 'computing', 'LG', 349.00, 'EUR', 14, 0, now(), now()),
    (gen_random_uuid(), 'Samsung T7 Portable SSD 1TB', 'Pocket-sized USB 3.2 external solid state drive with 1,050 MB/s transfers.', 'computing', 'Samsung', 99.90, 'EUR', 90, 0, now(), now()),
    (gen_random_uuid(), 'SanDisk Extreme microSD 256GB', 'Fast memory card for cameras, drones and handheld consoles.', 'computing', 'SanDisk', 29.99, 'EUR', 300, 0, now(), now()),
    (gen_random_uuid(), 'Anker 737 Power Bank', '24,000mAh portable charger with 140W USB-C output.', 'accessories', 'Anker', 109.99, 'EUR', 35, 0, now(), now()),
    (gen_random_uuid(), 'Anker Nano USB-C Charger 30W', 'Compact fast wall charger for phones and tablets.', 'accessories', 'Anker', 19.99, 'EUR', 400, 0, now(), now()),
    (gen_random_uuid(), 'Belkin BoostCharge Pro 3-in-1', 'Wireless charging stand for iPhone, Apple Watch and AirPods.', 'accessories', 'Belkin', 129.99, 'EUR', 15, 0, now(), now()),
    (gen_random_uuid(), 'Apple USB-C to Lightning Cable', 'One-metre cable for charging and syncing iPhone.', 'accessories', 'Apple', 25.00, 'EUR', 250, 0, now(), now()),
    (gen_random_uuid(), 'Spigen Tough Armor Phone Case', 'Dual-layer protective case with kickstand.', 'accessories', 'Spigen', 19.99, 'EUR', 500, 0, now(), now()),
    (gen_random_uuid(), 'Apple iPad Air 11-inch', 'Thin and light tablet with M2 chip and Liquid Retina display.', 'tablets', 'Apple', 699.00, 'EUR', 11, 0, now(), now()),
    (gen_random_uuid(), 'Samsung Galaxy Tab S9 FE', 'Water-resistant Android tablet with S Pen included.', 'tablets', 'Samsung', 449.00, 'EUR', 16, 0, now(), now()),
    (gen_random_uuid(), 'Amazon Kindle Paperwhite', 'Waterproof e-reader with 6.8-inch glare-free display.', 'tablets', 'Amazon', 169.99, 'EUR', 55, 0, now(), now()),
    (gen_random_uuid(), 'Garmin Forerunner 265', 'GPS running smartwatch with AMOLED display and training readiness.', 'wearables', 'Garmin', 449.99, 'EUR', 10, 0, now(), now()),
    (gen_random_uuid(), 'Apple Watch SE', 'Smartwatch with crash detection, heart-rate notifications and fitness tracking.', 'wearables', 'Apple', 279.00, 'EUR', 20, 0, now(), now()),
    (gen_random_uuid(), 'Fitbit Inspire 3', 'Slim fitness tracker with 10-day battery and sleep tracking.', 'wearables', 'Fitbit', 89.95, 'EUR', 65, 0, now(), now()),
    (gen_random_uuid(), 'Xiaomi Smart Band 8', 'Affordable fitness band with 16-day battery life.', 'wearables', 'Xiaomi', 39.99, 'EUR', 140, 0, now(), now()),
    (gen_random_uuid(), 'GoPro HERO12 Black', 'Waterproof action camera with 5.3K video and HyperSmooth stabilisation.', 'cameras', 'GoPro', 449.99, 'EUR', 7, 0, now(), now()),
    (gen_random_uuid(), 'DJI Osmo Pocket 3', 'Pocket gimbal camera with 1-inch sensor and 4K/120fps video.', 'cameras', 'DJI', 539.00, 'EUR', 0, 0, now(), now()),
    (gen_random_uuid(), 'Instax Mini 12 Instant Camera', 'Fun instant camera with automatic exposure and selfie mode.', 'cameras', 'Fujifilm', 79.99, 'EUR', 48, 0, now(), now()),
    (gen_random_uuid(), 'Nintendo Switch OLED', 'Hybrid game console with a vibrant 7-inch OLED screen.', 'gaming', 'Nintendo', 349.99, 'EUR', 19, 0, now(), now()),
    (gen_random_uuid(), 'Xbox Wireless Controller', 'Wireless game controller with textured grip and hybrid D-pad.', 'gaming', 'Microsoft', 59.99, 'EUR', 85, 0, now(), now()),
    (gen_random_uuid(), 'PlayStation DualSense Wireless Controller', 'Controller with haptic feedback and adaptive triggers.', 'gaming', 'Sony', 74.99, 'EUR', 60, 0, now(), now());
