spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/products
    username: products
    password: products
  elasticsearch:
    uris: http://localhost:9200

management:
  endpoint:
    health:
      show-details: always

logging:
  structured:
    format:
      console: ""

search:
  refresh: wait_for
