spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/products
    username: products
    password: products
management:
  endpoint:
    health:
      show-details: always

logging:
  structured:
    format:
      console: ""
