apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: product-search
resources:
- ../../base
images:
- name: product-search
  newName: ghcr.io/divya-somashekar/product-search
  newTag: c1b5a1f91924
